// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ioxoiahhfprwqexccelg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlveG9pYWhoZnByd3FleGNjZWxnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA2NTMzNzAsImV4cCI6MjA4NjIyOTM3MH0.4VNgJF79XmUrp-CE_dKdNJ04voIfvySgEpCv-dTs9zE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});